services:
  web:
    build:
      dockerfile: Dockerfile
      target: deploy
    env_file:
      - ./docker.env
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
